#!/usr/bin/env node

var child_process = require('child_process'),
  Path = require('path');

var ptr = Path.relative(process.cwd(), Path.join(__dirname, '..', 'scripts', 'allex-mocha-runner')),
  iswindows = process.platform.indexOf('win') == 0;

var ar = iswindows ?
  child_process.spawn('cmd.exe', ['/c', 'allexrun', ptr, process.argv[2]], {stdio:'inherit'})
  :
  child_process.spawn('allexrun', [ptr, process.argv[2]], {stdio:'inherit'});
ar.on('close', function (code) {
  process.exit(code);
});
